### ISSUE TITLE
Cannot get this to work with my data

### ISSUE THREAD

**Issue by ChaseTaylor939** [combio-dku/HiCAT#2]
I notice when you load the example "Melanoma_5k_rev.h5ad" it already has obs, var, and uns present in the file.  Can you provide some guidance on how you processed your data to get it to this point?  I have filtered_feature_bc_matrix.h5 files that I typically start my analysis from when analyzing with Scanpy.  When I run HiCAT after processing my data I get the follow error:

```
## Marker file to use
mkr_file = '/mnt/c/Users/taylor81/Desktop/Scanpy/Multiome_9045-CT-1/cell_markers_rndsystems.tsv'

# df_pred, summary = \
#     HiCAT( X, marker_file = mkr_file, log_transformed = False,
#                    Clustering_algo = 'lv', Clustering_resolution = 1, 
#                    Target_FPR = 0.05, pval_th = 0.05,
#                    target_cell_types = [], ## all in the db
#                    minor_types_to_exclude = [], N_neighbors_minor = 21,
#                    N_neighbors_subset = 1, cycling_cell = False, 
#                    verbose = False )

target_tissues = [] # ['Immune', 'General']
target_cell_types = ['T cell', 'B cell', 'Myeloid cell', 'Fibroblast',
                     'Epithelial cell', 'Endothelial cell', 
                     'Mast cell', 'Smooth muscle cell'] 
to_exclude = [] 

df_pred, summary = \
    HiCAT( X, mkr_file, log_transformed = False,
           target_tissues = target_tissues, target_cell_types = target_cell_types, 
               minor_types_to_exclude = to_exclude, mkr_selector = '100000', 
               N_neighbors_minor = 31, N_neighbors_subset = 1,  
               Clustering_algo = 'lv', Clustering_resolution = 1, 
               Clustering_base = 'pca', N_pca_components = 15, 
               cbc_cutoff = 0.01, Target_FPR = 0.05, pval_th = 0.05,
               cycling_cell = False, copy_X = False, verbose = False )
```

```
ValueError: Input X contains NaN.
PCA does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

```
Thank you in advance for all your help.

**Comment by combio-dku** [comment]
Hi, Chase, again
The error message looks your data frame, X, contains NaN.
X should be a DataFrame with its columns being gene names (Hugo symbols) and its index being cell barcodes.
Although there is no restriction in cell barcodes, the column names must be gene names, similar to those in marker file.

As shown in the example jupyter notebook file, .h5ad file can be read out as AnnData format, (using `scanpy.read_h5ad()` method), from which the cell-by-gene matrix (actually a DataFrame), X, can be obtained by `to_df()` method.
By using `to_df()` method, the data fram X has gene symbols (Hugo symbols) as its columns and cell barcode as its index.

By the way, I don't use .h5 file format and have no idea on its format.
Easiest way to get a proper X might be you first need to get AnnData stored in a .h5ad file, where
the index of .var must be gene names (Hugo symbols).

To make sure your DataFrame, X, does not contain NaN, you can check if `X.isnull().sum().sum()` is equal to 0.
Otherwise, you will need to remove those columns and rows that contain NaN before feeding it to HiCAT.

I hope this may be a help.
