### ISSUE TITLE
about example data

### ISSUE THREAD

**Issue by nbnbhwyy** [combio-dku/HiCAT#3]
I would like to ask if I don't seem to find the subset tag in the sample data, only 'celltype_major' and 'celltype_minor'.

In addition, results from other methods are provided in the data, and I found that the different methods predicted a large disparity in the number of classes. However, these methods are based on marker data for classification, and removing the effect of unknown types, they should predict the same number of classes, right? I hope to get your help.

**Comment by combio-dku** [comment]
Hi
'celltype_major' and 'celltype_minor' are the manual annotation. They were created from the original manual annotation in 'celltype' column in obs field. I just renamed them to compare with HiCAT results.
HiCAT results are stored in 'HiCAT_major', 'HiCAT_minor' and 'HiCAT_subset', where the first two can be compared with the manual annotations to evaluate accuracy.
Regarding the question "However, these methods ...., right?", Yes, exactly, because I used the same markers (at different level) for all the tools I ran.
If you want to run other annotation tools I used, you can use the R wrapper package RCTI_collection at https://github.com/combio-dku/RCTIcollection
